FROM python:3.9-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \ 
    build-essential \ 
    wget \ 
    && rm -rf /var/lib/apt/lists/*

COPY source_code/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8181

CMD ["gunicorn", "--bind", "0.0.0.0:8181",  "server:app"]
