events {}

http {
    include mime.types;

    upstream flask_app {
        server localhost:8181;
    }

    server {
        listen 80;

        # Serve static files directly
        location /static/ {
            alias /home/ubuntu/Two_tier_deployment/source_code/static/;
        }

        # Forward all other requests to Flask
        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
