events {}

http {
    include mime.types;

    upstream flask_app {
        server flask-app:8181;
    }

    server {
        listen 80;

        # Serve static files directly
        location /static/ {
            alias /app/static/;
        }

        # Forward all other requests to Flask
        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
